{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"fato_bolsa_familia\",\"dim_regioes\",\"dim_usuarios_rls\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_2f18a698-3ae0-4fb9-b78d-dc6a939d0ae1",
        "fromColumn": "UF",
        "fromTable": "fato_bolsa_familia",
        "toColumn": "UF",
        "toTable": "dim_regioes"
      },
      {
        "name": "22123405-9822-cd1b-b7d6-0a9b8b8f0a9f",
        "fromColumn": "Regiao",
        "fromTable": "dim_regioes",
        "toColumn": "regiao_permitida",
        "toTable": "dim_usuarios_rls"
      }
    ],
    "roles": [
      {
        "name": "Admin",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "2590010afeff497bbcea562c8a688fed"
          }
        ],
        "modelPermission": "read"
      },
      {
        "name": "Gestor_Nordeste",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "2440c0c5246a48eabee0b5937d728a82"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "dim_regioes",
            "filterExpression": "[Regiao] == \"Nordeste\""
          }
        ]
      },
      {
        "name": "Gestor_Norte",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8504a7f5fcc54da6863e0e44570f0f3d"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "dim_regioes",
            "filterExpression": "[Regiao] == \"Norte\""
          }
        ]
      },
      {
        "name": "Gestor_CentroOeste",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "36187c8e33304ce0af8df5f86cf2a855"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "dim_regioes",
            "filterExpression": "[Regiao] == \"CentroOeste\""
          }
        ]
      },
      {
        "name": "Gestor_Sudeste",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d772ac36b2044a83b63839cacdb8f372"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "dim_regioes",
            "filterExpression": "[Regiao] == \"Sudeste\""
          }
        ]
      },
      {
        "name": "Gestor_Sul",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1e113f5938d64329844708379cdeb03a"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "dim_regioes",
            "filterExpression": "[Regiao] == \"Sul\""
          }
        ]
      },
      {
        "name": "Gestor_Regional_Dinamico",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "109e5fca100b4879bb8401762c607fa7"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "dim_usuarios_rls",
            "filterExpression": "[email_usuario] = USERPRINCIPALNAME()"
          }
        ]
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "fato_bolsa_familia",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "MÊS COMPETÊNCIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ca310fe1-fb1e-4bac-9fa0-a7b11052f583",
            "sourceColumn": "MÊS COMPETÊNCIA",
            "summarizeBy": "sum"
          },
          {
            "name": "ANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e024605a-cfda-4451-8c79-fe578a12e633",
            "sourceColumn": "ANO",
            "summarizeBy": "none"
          },
          {
            "name": "MES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2494a039-4e4c-4b05-a9cc-3c220aa7023b",
            "sourceColumn": "MES",
            "summarizeBy": "none"
          },
          {
            "name": "UF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3130fb4a-3e61-435a-87ad-358c6e7c0459",
            "sourceColumn": "UF",
            "summarizeBy": "none"
          },
          {
            "name": "CÓDIGO MUNICÍPIO SIAFI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a37997b6-45ae-4315-a9dd-6de31b6c05e2",
            "sourceColumn": "CÓDIGO MUNICÍPIO SIAFI",
            "summarizeBy": "sum"
          },
          {
            "name": "NOME MUNICÍPIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "976c6080-c091-4889-935b-41f0132e0c0f",
            "sourceColumn": "NOME MUNICÍPIO",
            "summarizeBy": "none"
          },
          {
            "name": "CPF FAVORECIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11e7ef10-515f-4e8b-827a-5a46b0bf1cd9",
            "sourceColumn": "CPF FAVORECIDO",
            "summarizeBy": "none"
          },
          {
            "name": "NIS FAVORECIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1d8d8d6c-ffcb-4dd5-9a47-555555b80be9",
            "sourceColumn": "NIS FAVORECIDO",
            "summarizeBy": "sum"
          },
          {
            "name": "NOME FAVORECIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fa00efe-a79b-4e8f-9729-ef87c4667829",
            "sourceColumn": "NOME FAVORECIDO",
            "summarizeBy": "none"
          },
          {
            "name": "VALOR PARCELA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4609c66b-0879-4aef-b61b-9f443e48b994",
            "sourceColumn": "VALOR PARCELA",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b54c36d0-571d-44a2-b6ab-0ca0c401b2f1",
        "measures": [
          {
            "name": "Total Repasses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUM(fato_bolsa_familia[VALOR PARCELA])"
            ],
            "lineageTag": "857d17fb-d36f-4cfe-81e5-af4572debfa2"
          },
          {
            "name": "Total Beneficiarios",
            "expression": [
              "",
              "DISTINCTCOUNT(fato_bolsa_familia[NIS FAVORECIDO])"
            ],
            "formatString": "0",
            "lineageTag": "337ac194-98b2-4e2f-a73f-724f36fec2c7"
          },
          {
            "name": "Ticket Medio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "AVERAGE(fato_bolsa_familia[VALOR PARCELA])"
            ],
            "lineageTag": "3ef5cdc0-c255-4a8f-a729-84f9e3ebb019"
          },
          {
            "name": "Municipios Atendidos",
            "expression": [
              "",
              "DISTINCTCOUNT(fato_bolsa_familia[NOME MUNICÍPIO])"
            ],
            "formatString": "0",
            "lineageTag": "0ccd6be7-79ec-4a06-9346-2fcfbe7d9d4c"
          }
        ],
        "partitions": [
          {
            "name": "fato_bolsa_familia",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\joaofafa\\Downloads\\amostra_bolsa.csv\"),[Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"MÊS COMPETÊNCIA\", Int64.Type}, {\"UF\", type text}, {\"CÓDIGO MUNICÍPIO SIAFI\", Int64.Type}, {\"NOME MUNICÍPIO\", type text}, {\"CPF FAVORECIDO\", type text}, {\"NIS FAVORECIDO\", Int64.Type}, {\"NOME FAVORECIDO\", type text}, {\"VALOR PARCELA\", type number}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Tipo Alterado\", \"Ano\", each Text.Start(Text.From([MÊS COMPETÊNCIA]),4)),",
                "    #\"Colunas Reordenadas\" = Table.ReorderColumns(#\"Personalização Adicionada\",{\"MÊS COMPETÊNCIA\", \"Ano\", \"UF\", \"CÓDIGO MUNICÍPIO SIAFI\", \"NOME MUNICÍPIO\", \"CPF FAVORECIDO\", \"NIS FAVORECIDO\", \"NOME FAVORECIDO\", \"VALOR PARCELA\"}),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Colunas Reordenadas\", \"MES\", each Text.End(Text.From([MÊS COMPETÊNCIA]),2)),",
                "    #\"Colunas Reordenadas1\" = Table.ReorderColumns(#\"Personalização Adicionada1\",{\"MÊS COMPETÊNCIA\", \"Ano\", \"MES\", \"UF\", \"CÓDIGO MUNICÍPIO SIAFI\", \"NOME MUNICÍPIO\", \"CPF FAVORECIDO\", \"NIS FAVORECIDO\", \"NOME FAVORECIDO\", \"VALOR PARCELA\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Reordenadas1\",{{\"Ano\", \"ANO\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_0388b4cb-f5d1-4f1d-9434-d11885755a97",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "61bf350b-7fb2-4ac0-a3bb-1325577be3da",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4e3363c2-2e23-4fc3-9a23-e42d7c190f6a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2c1573dd-f16c-453d-a946-b12154529ae5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "bd2d93d8-c115-4206-9579-0e02ccdd029a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "48e03912-b8dc-4538-bc7d-98dcb4e7e8a9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d99182d7-a756-4ec2-a41c-15bca4b24bcc",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e4817517-6933-48cb-ad45-b89972374567",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "089e4637-4b76-4933-8a92-2882e0934888",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "d532c8b5-94f3-4bba-a0d7-4389d32f8102",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "88f32b44-58bc-4ce5-a070-e0db3208dc27",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "a954a56a-a59e-4699-b768-17e85118fd87",
                "ordinal": 3
              }
            ],
            "lineageTag": "4b324350-72c3-4f1b-9232-dccef03b9ac8"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "fcc50c59-cd38-4737-9941-d1b75e2b232e",
        "partitions": [
          {
            "name": "DateTableTemplate_0388b4cb-f5d1-4f1d-9434-d11885755a97",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dim_regioes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Regiao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f03faec9-6af6-431d-945c-7e14bf34deb9",
            "sourceColumn": "Regiao",
            "summarizeBy": "none"
          },
          {
            "name": "UF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ec516dd-934b-41d7-bdce-a972919946cb",
            "sourceColumn": "UF",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8abbbdbd-f540-4f7a-a745-e2db0fd7a271",
        "partitions": [
          {
            "name": "dim_regioes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(",
                "        {",
                "            {\"Norte\", \"AC\"},",
                "            {\"Norte\", \"AM\"},",
                "            {\"Norte\", \"AP\"},",
                "            {\"Norte\", \"PA\"},",
                "            {\"Norte\", \"RO\"},",
                "            {\"Norte\", \"RR\"},",
                "            {\"Norte\", \"TO\"},",
                "            {\"Nordeste\", \"AL\"},",
                "            {\"Nordeste\", \"BA\"},",
                "            {\"Nordeste\", \"CE\"},",
                "            {\"Nordeste\", \"MA\"},",
                "            {\"Nordeste\", \"PB\"},",
                "            {\"Nordeste\", \"PE\"},",
                "            {\"Nordeste\", \"PI\"},",
                "            {\"Nordeste\", \"RN\"},",
                "            {\"Nordeste\", \"SE\"},",
                "            {\"Centro-Oeste\", \"DF\"},",
                "            {\"Centro-Oeste\", \"GO\"},",
                "            {\"Centro-Oeste\", \"MS\"},",
                "            {\"Centro-Oeste\", \"MT\"},",
                "            {\"Sudeste\", \"ES\"},",
                "            {\"Sudeste\", \"MG\"},",
                "            {\"Sudeste\", \"RJ\"},",
                "            {\"Sudeste\", \"SP\"},",
                "            {\"Sul\", \"PR\"},",
                "            {\"Sul\", \"RS\"},",
                "            {\"Sul\", \"SC\"}",
                "        },",
                "        {\"Regiao\", \"UF\"}",
                "    )",
                "in",
                "    Fonte"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_usuarios_rls",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "email_usuario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "044bc330-60fa-4def-95a1-303b26d21340",
            "sourceColumn": "email_usuario",
            "summarizeBy": "none"
          },
          {
            "name": "regiao_permitida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb10cba2-fe67-4e44-8b1d-e50e023d1797",
            "sourceColumn": "regiao_permitida",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "810642b6-6797-40c8-8bba-2692bf2ba0b0",
        "partitions": [
          {
            "name": "dim_usuarios_rls",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(",
                "        {",
                "            {\"gestor.norte@ministerio.br\", \"Norte\"},",
                "            {\"gestor.nordeste@ministerio.br\", \"Nordeste\"},",
                "            {\"gestor.centroeste@ministerio.br\", \"Centro-Oeste\"},",
                "            {\"gestor.sudeste@ministerio.br\", \"Sudeste\"},",
                "            {\"gestor.sul@ministerio.br\", \"Sul\"}",
                "        },",
                "        {\"email_usuario\", \"regiao_permitida\"}",
                "    ),",
                "",
                "    TipoAlterado = Table.TransformColumnTypes(",
                "        Fonte,",
                "        {",
                "            {\"email_usuario\", type text},",
                "            {\"regiao_permitida\", type text}",
                "        }",
                "    )",
                "in",
                "    TipoAlterado"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}